title: "OCI Terraform  Configuration "
description: "Stack to deploy resources in OCI Tenancy"
stackDescription: "Stack to deploy resources in OCI Tenancy"
schemaVersion: 1.1.0
version: "20201125"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - user_ocid
  - fingerprint
  - private_key_path
  - region
  

- title: "Required Configuration"
  visible: true  
  variables:
  - customer_label
  - compartment_id
  - compartment_id_db
  - subnet_id
  - data_storage_size_in_gb
  - db_shapes
  - db_shape_ocpus
  - db_shape_mem
  - ssh_key_db


- title: "Network Security Groups(DB1)"
  visible: 
      and:
        - show_advanced
  variables:
  - nsg1_db
  - nsg2_db
  - nsg3_db

- title: "Network Security Groups(DB2)"
  visible: 
      and:
        - show_advanced
  variables:
  - nsg1_db2
  - nsg2_db2
  - nsg3_db2

  


variables:

  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your tenancy"
    type: string
    required: true
    visibile: false

  region:
    title: "Region"
    description: "Choose Region where you deploy your application"
    type: oci:identity:region:name
    required: true
    visibile: true
  
 


  # Required Configuration(OpsView and Bastion)

  customer_label:
    title: "customer label"
    description: "Label used as a prefix for naming resources"
    type: string
    required: true
    visible: true

  compartment_id:
    title: "Compartment OCID"
    description: "Choose NSG Comparment "
    type: oci:identity:compartment:id
    required: true
    visibile: true

  compartment_id_db:
    title: "Compartment OCID"
    description: "Choose Comparment where you deploy your DB"
    type: oci:identity:compartment:id
    required: true
    visibile: true

  subnet_id:
    title: "Subnet OCID"
    description: "Choose subnet where you deploy your DB"
    type: oci:core:subnet:id
    required: true
    visibile: true
    dependsOn: 
      compartmentId: ${compartment_id}


  data_storage_size_in_gb:
    type: number
    required: false
    default: 100
    title: "Database storage size in GB"
    description: "Choose database storage size in GB for your DBSystem."

  db_shapes:
    type: oci:core:instanceshape:name
    title: "Instance Shape"
    description: "Choose a shape for your instance"
    default: "VM.Standard.E2.2"
    required: false
    dependsOn:
      compartmentId: ${compartment_id}


  ssh_key_db:
    title: SSH Public Key
    description: The public SSH key for the key-pair that you want to use, if you wish to login to the instances over SSH
    # renders variable as an SSH key control
    type: oci:core:ssh:publickey
    required: true

  db_shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 2
    title: " Shape OCPUs"
    description: "Choose number of OCPUs for Shape."

  db_shape_mem:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 16
    title: "DB Shape Mem"
    description: "DB Shape Mem"



  #NSG DB1
  nsg1_db:
    title: "Network security groups"
    description: "Network security groups for DEV DB"
    type: oci:core:nsg:id
    required: false
    visible: true
    dependsOn: 
      compartmentId: ${compartment_id}
  
  nsg2_db:
    title: "Network security groups"
    description: "Network security groups for DEV DB"
    type: oci:core:nsg:id
    required: false
    visible: true
    dependsOn: 
      compartmentId: ${compartment_id}

  nsg3_db:
    title: "Network security groups"
    description: "Network security groups for DEV DB"
    type: oci:core:nsg:id
    required: false
    visible: true
    dependsOn: 
      compartmentId: ${compartment_id}

#NSG DB1
  nsg1_db2:
    title: "Network security groups"
    description: "Network security groups for DEV DB"
    type: oci:core:nsg:id
    required: false
    visible: true
    dependsOn: 
      compartmentId: ${compartment_id}
  
  nsg2_db2:
    title: "Network security groups"
    description: "Network security groups for DEV DB"
    type: oci:core:nsg:id
    required: false
    visible: true
    dependsOn: 
      compartmentId: ${compartment_id}

  nsg3_db2:
    title: "Network security groups"
    description: "Network security groups for DEV DB"
    type: oci:core:nsg:id
    required: false
    visible: true
    dependsOn: 
      compartmentId: ${compartment_id}


  